### ISSUE TITLE
“UILayoutPriorityDefaultLow”已经被重命名为“UILayoutPriority.defaultLow”

### ISSUE THREAD

**Issue by daodaidao** [TMTBO/TTADataPickerView#2]
UILayoutPriorityDefaultLow ？？？

**Comment by daodaidao** [comment]
麻烦更新下库，不然pod 安装后，一直提示  UILayoutPriorityDefaultLow 。 这样的话 每次 pod update的时候就要忽略掉 你的库了。

Trouble updating the library, or pod after installation, always prompt UILayoutPriorityDefaultLow. This way, your library will be ignored every time pod update

**Comment by TMTBO** [comment]
0.4.0 has update the pod to swift 4.2
